# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\E-drive-12031\My_place\Github\Python_Chinese_Review_NoticeCenter\Notice.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(False)
        MainWindow.resize(250, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 246, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.time_bar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.time_bar.setContentsMargins(0, 0, 0, 0)
        self.time_bar.setObjectName("time_bar")
        self.time = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.time.setObjectName("time")
        self.time_bar.addWidget(self.time)
        self.time_tick = QtWidgets.QHBoxLayout()
        self.time_tick.setObjectName("time_tick")
        self.h = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.h.setObjectName("h")
        self.time_tick.addWidget(self.h)
        self.sep_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.sep_1.setFont(font)
        self.sep_1.setObjectName("sep_1")
        self.time_tick.addWidget(self.sep_1)
        self.m = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.m.setObjectName("m")
        self.time_tick.addWidget(self.m)
        self.sep_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.sep_2.setFont(font)
        self.sep_2.setObjectName("sep_2")
        self.time_tick.addWidget(self.sep_2)
        self.s = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.s.setObjectName("s")
        self.time_tick.addWidget(self.s)
        self.time_bar.addLayout(self.time_tick)
        self.time_left = QtWidgets.QProgressBar(self.centralwidget)
        self.time_left.setGeometry(QtCore.QRect(0, 340, 251, 23))
        self.time_left.setMaximum(300)
        self.time_left.setProperty("value", 300)
        self.time_left.setTextVisible(False)
        self.time_left.setObjectName("time_left")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "提示"))
        self.time.setText(_translate("MainWindow", "现在是： 北京时间(UTC+8):"))
        self.sep_1.setText(_translate("MainWindow", ":"))
        self.sep_2.setText(_translate("MainWindow", ":"))
